### ISSUE TITLE
Add assertions

### ISSUE THREAD

**Issue by ReggieLai** [hdengg/MysteryBox_CS304#10]
Add assertions to bolded lines in SQL file

**Comment by hdengg** [comment]
@sajjan19 Hey Mandeep. For the bold lines, we need assertion statements to capture the total participation constraint in our SQL file. There are examples on the lecture slides as well.

**Comment by sajjan19** [comment]
Okay Im working on that right now. Did you change the relation between Subscripton and MysterBox?
